# Generated by Django 6.0.1 on 2026-03-11 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(max_length=4, unique=True)),
                ('iata_code', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=6, default=1.0, max_digits=15)),
                ('symbol', models.CharField(default='$', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_round', models.IntegerField(default=0)),
                ('cost_of_credit_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('conversion_to_usg', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calculation_method', models.CharField(choices=[('UNIT', 'Per Unit'), ('UPTAKE', 'Per Uptake')], max_length=10)),
                ('category', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('CONDITIONAL', 'Conditional')], max_length=15)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='procurement.airport')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differential_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('reference_price_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('price_basis', models.CharField(default='CIF NWE HIGH', max_length=100)),
                ('taxes_total', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('tax_breakdown', models.TextField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=15)),
                ('invoicing_frequency', models.IntegerField(default=30)),
                ('credit_period', models.IntegerField(default=30)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('round_number', models.IntegerField(default=1)),
                ('volume_percentage_offered', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.airline')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.airport')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.currency')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.supplier')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.tender')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.unitofmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('volume_usg', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('uptakes_per_year', models.IntegerField(default=365)),
                ('is_submitted', models.BooleanField(default=False)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.airline')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.airport')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.tender')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.unitofmeasure')),
            ],
        ),
    ]
