# Generated by Django 5.2.7 on 2026-07-20 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_tender_show_live_ranking_alter_airline_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('business_registration', 'Business Registration'), ('insurance', 'Insurance Certificate'), ('other', 'Other Supporting Document')], max_length=50)),
                ('file', models.FileField(upload_to='supplier_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='procurement.supplier')),
            ],
        ),
    ]
