# Generated by Django 6.0.1 on 2026-08-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_add_insured_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='volumes_released',
            field=models.BooleanField(default=False, help_text='If True, suppliers can see the volumes and place bids.'),
        ),
    ]
